#!/usr/bin/env node

/* generate by git-pre-hooks */
'use strict';

var child = require('child_process');
var path = require('path');

var command = path.basename(__filename);

child.exec('git rev-parse --show-toplevel', function (err, stdout) {
  if (err) return error(err);

  var root = stdout.trim();
  var pkg;
  try {
    pkg = require(path.join(root, 'package.json'));
  } catch (err) {
    return error(err);
  }

  // no task to run
  if (!pkg || !pkg.hooks || !pkg.hooks[command] || !pkg.hooks[command].length) return;

  run(root, pkg.hooks[command]);
});

function run(root, tasks) {
  if (typeof tasks === 'string') tasks = [tasks];
  if (!Array.isArray(tasks)) {
    return error(new Error('hooks.' + command + ' in package.json must be string or array'));
  }

  next();

  function next() {
    if (tasks.length === 0) return;

    var task = tasks.shift();
    child.exec(task, { cwd: root }, function (err, stdout) {
      if (err) {
        err.task = task;
        return error(err);
      }
      process.stdout.write(stdout);
      next(root, tasks);
    });
  }
}

function error(err) {
  if (err.task) console.error('[%s] run `%s` error', command, err.task);
  console.error('[%s] Error Stack:\n%s', command, err.stack.replace(/^/gm, '  '));
}
